#!/usr/bin/python


def build_mach():
    pass


# Setup callback functions
build_actions['build_mach'] = build_mach

# Setup mach options
build_opts['dts'] = find_deepest_arch_file('dts/empty.dts')

build_opts['embed_fdt'] = False
build_opts['embed_coreimg'] = False

build_opts['qemu'] = {
    'machine'   : 'mac99',
    'memory'    : 512,
    'graphic'   : False,
    'bootargs'  : 'test',
    'bootimg'   : img_dir + 'tdlrboot.bin',
    'mp'        : '4',
}
